# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ricsanto <ricsanto@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/29 19:21:29 by ricsanto          #+#    #+#              #
#    Updated: 2025/04/30 12:14:03 by ricsanto         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

HEADER_DIR := header
HELPER_DIR := helper
PRINT_DIR := print
LIBFT_DIR := libft
