# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ricsanto <ricsanto@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/29 19:21:29 by ricsanto          #+#    #+#              #
#    Updated: 2025/04/29 19:41:03 by ricsanto         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

HEADER_DIR := header
HELPER_DIR := helper
PRINT_DIR := print
LIBFT_DIR := libft

LIBFT_SRC :=	$(LIBFT_DIR)/ft_isalpha.c		$(LIBFT_DIR)/ft_isdigit.c	$(LIBFT_DIR)/ft_isalnum.c		\
				$(LIBFT_DIR)/ft_isascii.c		$(LIBFT_DIR)/ft_isprint.c	$(LIBFT_DIR)/ft_strlen.c		\
				$(LIBFT_DIR)/ft_memset.c		$(LIBFT_DIR)/ft_bzero.c		$(LIBFT_DIR)/ft_memcpy.c		\
				$(LIBFT_DIR)/ft_memmove.c		$(LIBFT_DIR)/ft_strlcpy.c	$(LIBFT_DIR)/ft_strlcat.c		\
				$(LIBFT_DIR)/ft_toupper.c		$(LIBFT_DIR)/ft_tolower.c	$(LIBFT_DIR)/ft_strchr.c		\
				$(LIBFT_DIR)/ft_strrchr.c		$(LIBFT_DIR)/ft_strncmp.c	$(LIBFT_DIR)/ft_memchr.c		\
				$(LIBFT_DIR)/ft_memcmp.c		$(LIBFT_DIR)/ft_strnstr.c	$(LIBFT_DIR)/ft_atoi.c			\
				$(LIBFT_DIR)/ft_calloc.c		$(LIBFT_DIR)/ft_strdup.c	$(LIBFT_DIR)/ft_substr.c		\
				$(LIBFT_DIR)/ft_strjoin.c		$(LIBFT_DIR)/ft_strtrim.c	$(LIBFT_DIR)/ft_split.c			\
				$(LIBFT_DIR)/ft_itoa.c			$(LIBFT_DIR)/ft_strmapi.c	$(LIBFT_DIR)/ft_striteri.c		\
				$(LIBFT_DIR)/ft_putchar_fd.c	$(LIBFT_DIR)/ft_putstr_fd.c	$(LIBFT_DIR)/ft_putendl_fd.c	\
				$(LIBFT_DIR)/ft_putnbr_fd.c

HELPER_SRC :=	$(HELPER_DIR)/h_addtocounter.c	$(HELPER_DIR)/h_count_nbr.c	$(HELPER_DIR)/h_print_nbrbase	\
				$(HELPER_DIR)/h_printstr.c

PRINT_SRC :=	$(PRINT_DIR)/